version: "3"

services:

  rabbitmq:
    image: "rabbitmq:3.8-management-alpine"
    container_name: nodejs-rabbitmq-rabbitmq
    hostname: rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - "./.rabbitmq_data:/var/lib/rabbitmq/mnesia"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin

  consumer:
    build: ./consumer
    entrypoint: ./.docker/entrypoint.sh
    container_name: nodejs-rabbitmq-consumer
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - 3001:3000
    volumes:
      - ./consumer:/home/node/consumer
    depends_on: 
      - rabbitmq

  producer:
    build: ./producer
    entrypoint: ./.docker/entrypoint.sh
    container_name: nodejs-rabbitmq-producer
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - 3000:3000
    volumes:
      - ./producer:/home/node/producer
    depends_on: 
      - rabbitmq